using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerController : MonoBehaviour
{
    // 스피드 조절 변수
    [SerializeField]
    private float walkSpeed = 0;
    [SerializeField]
    private float runSpeed = 0;
    [SerializeField]
    private float crouchSpeed = 0;
    private float _applySpeed = 0;

    [SerializeField] private float jumpForce = 0;

    // 상태 변수
    private bool isWalk = false;
    private bool isRun = false;
    private bool isCrouch = false;
    private bool isGround = true;
    
    // 움직임 체크 변수
    private Vector3 lastPos;

    // 앉는 정도 변수
    [SerializeField]
    private float crouchPosY;
    private float originPosY;
    private float applyCrouchPosY;
    
    // 땅 착지 여부
    private CapsuleCollider capsuleCollider;

    // 민감도
    [SerializeField]
    private float lookSensitivity = 0;

    // 카메라 한계
    [SerializeField]
    private float cameraRotationLimit = 0;
    private float currentCameraRotationX = 0;

    // 필요한 컴포넌트
    [SerializeField]
    private Camera theCamera = null;
    private Rigidbody myRigid = null;
    private Crosshair theCrossghair;
    // Start is called before the first frame update
    void Start()
    {
        capsuleCollider = GetComponent<CapsuleCollider>();
        myRigid = GetComponent<Rigidbody>();
        theCrossghair = FindObjectOfType<Crosshair>();
        
        // 초기화
        _applySpeed = walkSpeed;
        originPosY = theCamera.transform.localPosition.y;
        applyCrouchPosY = originPosY;
    }

    // Update is called once per frame
    void Update()
    {
        IsGround();
        TryJump();
        TryRun();
        Move();
        TryCrouch();
        CameraRotation();
        CharacterRotation();
    }

    // 앉기 시도
    private void TryCrouch()
    {
        if (Input.GetKeyDown(KeyCode.LeftControl))
        {
            Crouch();
        }
    }

    // 앉기
    private void Crouch()
    {
        isCrouch = !isCrouch;
        theCrossghair.CrouchingAnimation(isCrouch);

        if (isCrouch)
        {
            _applySpeed = crouchSpeed;
            applyCrouchPosY = crouchPosY;
            
        }
        else
        {
            _applySpeed = walkSpeed;
            applyCrouchPosY = originPosY;
        }

        StartCoroutine(CrouchCoroutine());
    }

    // 부드러운 앉기
    IEnumerator CrouchCoroutine()
    {
        float _posY = theCamera.transform.localPosition.y;
        int count = 0;

        while (_posY != applyCrouchPosY)
        {
            count++;
            _posY = Mathf.Lerp(_posY, applyCrouchPosY, 0.3f);
            theCamera.transform.localPosition = new Vector3(0, _posY, 0);
            if (count > 15)
                break;
            yield return null;
        }
        theCamera.transform.localPosition = new Vector3(0, applyCrouchPosY, 0f);
    }

    // 지면 체크
    private void IsGround()
    {
        isGround = Physics.Raycast(transform.position, Vector3.down, capsuleCollider.bounds.extents.y + 0.2f);
        theCrossghair.JumpingAnimation(!isGround);
    }

    // 점프 시도
    private void TryJump()
    {
        if (Input.GetKeyDown(KeyCode.Space) && isGround)
        {
            Jump();
        }
    }

    // 점프
    private void Jump()
    {
        if (isCrouch)
            Crouch();
        
        myRigid.velocity = transform.up * jumpForce;
    }
    
    // 달리기 시도
    private void TryRun()
    {
        if (Input.GetKey(KeyCode.LeftShift))
        {
            Running();
        }

        if (Input.GetKeyUp(KeyCode.LeftShift))
        {
            RunningCancel();
        }
    }

    // 달리기
    private void Running()
    {
        if (isCrouch)
            Crouch();
        
        isRun = true;
        theCrossghair.RunningAnimation(isRun);
        _applySpeed = runSpeed;
    }

    // 달리기 취소
    private void RunningCancel()
    {
        isRun = false;
        theCrossghair.RunningAnimation(isRun);
        _applySpeed = walkSpeed;
    }

    // 움직이기
    private void Move()
    {
        float moveDirX = Input.GetAxisRaw("Horizontal");
        float moveDirZ = Input.GetAxisRaw("Vertical");

        Vector3 moveHorizontal = transform.right * moveDirX;
        Vector3 moveVertical = transform.forward * moveDirZ;
        Vector3 velocity = (moveHorizontal + moveVertical).normalized * _applySpeed;
        
        myRigid.MovePosition(transform.position + velocity * Time.deltaTime);

        MoveCheck(velocity);
    }

    private void MoveCheck(Vector3 velocity)
    {
        if (!isRun && !isCrouch && isGround)
        {
            if (velocity.magnitude >= 0.1f)
            {
                isWalk = true;
            }
            else
            {
                isWalk = false;
            }
            
            theCrossghair.WalkingAnimation(isWalk);
        }
    }

    // 카메라 상하 회전
    private void CameraRotation()
    {
        float xRotation = Input.GetAxisRaw("Mouse Y");
        float cameraRotationX = xRotation * lookSensitivity;
        currentCameraRotationX -= cameraRotationX;
        currentCameraRotationX = Mathf.Clamp(currentCameraRotationX, -cameraRotationLimit, cameraRotationLimit);
        
        theCamera.transform.localEulerAngles = new Vector3(currentCameraRotationX, 0f, 0f);
    }

    // 카메라 좌우 회전
    private void CharacterRotation()
    {
        float yRotation = Input.GetAxisRaw("Mouse X");
        Vector3 characterRotationY = new Vector3(0f, yRotation, 0f) * lookSensitivity;
        myRigid.MoveRotation(myRigid.rotation * Quaternion.Euler(characterRotationY));
    }
    
    // 상태 변수 값 반환
    public bool GetRun()
    {
        return isRun;
    }

    public bool GetWalk()
    {
        return isWalk;
    }

    public bool GetCrouch()
    {
        return isCrouch;
    }

    public bool GetIsGround()
    {
        return isGround;
    }
}
